### ISSUE TITLE
Clarifying `publicKeyMultibase` encoding: `did:key` style with multicodec code, or not?

### ISSUE THREAD

**Issue by bnewbold** [w3c/vc-di-ecdsa#26]
With the `did:plc` method, we have been returning `verificationMethod` objects with type `EcdsaSecp256k1VerificationKey2019` and a `publicKeyMultibase` string encoding with:

* multibase prefix char `z`, indicating base58btc encoding
* followed directly by the string encoded, un-compressed curve public key bytes

This is a different encoding from that used for `did:key`, which includes a varint multiformat table value indicating the specific key type, and compressed curve public key bytes.

For example:

```
{
  "id": "#atproto",
  "type": "EcdsaSecp256k1VerificationKey2019",
  "controller": "did:plc:yk4dd2qkboz2yv6tpubpc6co",
  "publicKeyMultibase": "zQYEBzXeuTM9UR3rfvNag6L3RNAs5pQZyYPsomTsgQhsxLdEgCrPTLgFna8yqCnxPpNT7DBk6Ym3dgPKNu86vt9GR"
}
```

where the corresponding key has `did:key` format: `did:key:zQ3shXjHeiBuRCKmM36cuYnm7YEMzhGnCmCyW92sRJ9pribSF`.

I had assumed that the un-compressed key format was required in a DID specification document somewhere, but when I went looking just now, could find no reference in [the Core 1.0 doc](https://w3c.github.io/did-core/), https://www.w3.org/TR/did-spec-registries, Verifiable [Credential Data Integrity 1.0 ](https://w3c.github.io/vc-data-integrity), etc. The last link *does* talk about how the `Multikey` method specifically requires a `publicKeyMultibase` encoding with the multicodec included, but doesn't mention how other types like `EcdsaSecp256k1VerificationKey2019` should be encoded.

This github issue is asking to clarify: is there required multibase format? is it ok to use the multicodec-based encoding, as used with `did:key` and `Multikey`?

**Comment by msporny** [comment]
> is there required multibase format? 

The cryptosuite that uses the key type will define the required multibase format. For example, here's the one for Ed25519 public keys:

https://w3c.github.io/vc-di-eddsa/#multikey

and the one for ECDSA public keys:

https://w3c.github.io/vc-di-ecdsa/#multikey

One doesn't exist for k1 keys because no one has written that particular spec yet, but I'd expect it to use the bitcoin base58 header 'z' and  the `0xe7` multikey header (remember to encode as a varint!) with a compressed key: 

https://github.com/multiformats/multicodec/blob/master/table.csv#L92

> is it ok to use the multicodec-based encoding, as used with did:key and Multikey?

Yes, in fact, the Multikey encoding of a did:key should be exactly the same. did:key uses the Multikey format.

**Comment by bnewbold** [comment]
Yes, thank you for such a clear response!

**Comment by msporny** [comment]
This issue is fairly old and the question was answered some time ago. Seems like discussion on the issue has ended. I'm closing this issue. @bnewbold, please re-open a new issue if there is further discussion to be had.
