### ISSUE TITLE
Remove references to MULTIBASE and MULTICODEC

### ISSUE THREAD

**Issue by selfissued** [w3c/vc-di-ecdsa#39]
MULTIBASE and MULTICODEC are not standards.  Please replace uses of them with normative text defining the contents any fields using them.

This is related to https://github.com/w3c/vc-data-integrity/issues/191.

**Comment by msporny** [comment]
PR #42 has been raised to address this issue. This issue will be closed once PR #42 has been merged.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-09-27-vcwg#section2-1) on 2023-09-27

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.1. Remove references to MULTIBASE and MULTICODEC (issue vc-di-ecdsa#39)

_See github issue [vc-di-ecdsa#39](https://github.com/w3c/vc-di-ecdsa/issues/39)._




**Kristina Yasuda:** tldr; there was an issue coming in about normative references about multibase and multicodec. We agreed to fix that in the vcdm. Now there are issues about addressing them in the cryptosuite spec docs.  
… manu did a PR in which selfissued is asking for changes.  

</details>

**Comment by msporny** [comment]
PR #42 has been merged, closing.
